//login1
POST  http://localhost:8001/login
Content-Type: application/json

{
    "email": "7f345b0b3b@emaillab.xyz",
    "password": "123123"
}

###

//login 2
POST  http://localhost:8001/login
Content-Type: application/json

{
    "email": "7f345b0b3b@emaillab.xyz",
    "password": "123123"
}

###

//TOKEN
POST http://localhost:8001/token
Content-Type: application/json

{
    "token": ""
}

###
//GET USER INFO
GET http://localhost:8001/getUserInfo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRmlyZWZveCBNb3ppbGxhIiwibW9uZ29JRCI6IjVmMzcwYTY2ZTdhNmJiMWY5NGE1NDU4ZiIsImVtYWlsIjoiN2YzNDViMGIzYkBlbWFpbGxhYi54eXoiLCJ0eXBlIjoiYXR0b3JuZXkiLCJpbWciOiJhc3NldHMvdXNlckltYWdlcy8xNTk4NDA5NTk2MDUyNDY5NTAzMDE5MzEyNC5wbmciLCJpYXQiOjE2MDM1NTQzMjIsImV4cCI6MTYwMzU1NjEyMn0.NhMQ4yqeVdhyVAnuZ50IkktCdmidpiTnZXrupr1Abl8

###
//LOGUOT
DELETE http://localhost:8001/logout
Content-Type: application/json

{
    "token": ""
}
###

POST  http://localhost:8001/completeTask
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRmlyZWZveCBNb3ppbGxhIiwibW9uZ29JRCI6IjVmMzcwYTY2ZTdhNmJiMWY5NGE1NDU4ZiIsImVtYWlsIjoiN2YzNDViMGIzYkBlbWFpbGxhYi54eXoiLCJ0eXBlIjoiYXR0b3JuZXkiLCJpbWciOiJhc3NldHMvdXNlckltYWdlcy8xNTk4NDA5NTk2MDUyNDY5NTAzMDE5MzEyNC5wbmciLCJpYXQiOjE2MDE4NTc2MDAsImV4cCI6MTYwMTk4NjQwMH0.HilAxLc_DKbjiI1bhCyciKreAIdln1gTFIRPQ5peorw

{
    
  "taskName": "Dejar Nota",
  "expirationDate": "2020-10-31",
  "fileID": "123123"

    
}

###

POST http://localhost:8001/searchFileInBD?searchParameter=ASDASD
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRmlyZWZveCBEZXZlbG9wZXIgRWRpdGlvbiIsIm1vbmdvSUQiOiI1ZWZjOGUwOTE0YzJiMDEyM2MyYzlkYzIiLCJlbWFpbCI6ImIzMzU1MzM4NTZAZW1haWxtb25rZXkuY2x1YiIsInR5cGUiOiJyZXByZXNlbnRhdGl2ZSIsImltZyI6ImFzc2V0cy91c2VySW1hZ2VzLzE1OTg0MDk2NTc0OTAzMzQ4MjM0NzMxNzgxLnBuZyIsImlhdCI6MTYwMjUzOTc1OSwiZXhwIjoxMDAxNjAyNTM5NzU4fQ.0VW1H3OO-4SkdpY0a1Je211ejQ4Ty_6t1zFtW4oLnF4

###


POST http://localhost:8001/searchFriend?searchParameter=Developer Firefox Brave
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRmlyZWZveCBEZXZlbG9wZXIgRWRpdGlvbiIsIm1vbmdvSUQiOiI1ZWZjOGUwOTE0YzJiMDEyM2MyYzlkYzIiLCJlbWFpbCI6ImIzMzU1MzM4NTZAZW1haWxtb25rZXkuY2x1YiIsInR5cGUiOiJyZXByZXNlbnRhdGl2ZSIsImltZyI6ImFzc2V0cy91c2VySW1hZ2VzLzE1OTg0MDk2NTc0OTAzMzQ4MjM0NzMxNzgxLnBuZyIsImlhdCI6MTYwMjUzOTc1OSwiZXhwIjoxMDAxNjAyNTM5NzU4fQ.0VW1H3OO-4SkdpY0a1Je211ejQ4Ty_6t1zFtW4oLnF4